# The relative path to the flutter podhelper.rb
require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)

# Set platform to iOS 14.0
platform :ios, '14.0'

# CocoaPods analytics sends usage information to cocoapods.org.
# Uncomment this line to disable sending usage information.
# keep_silent!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
